system:
  port: "9090"

database:
  host: '127.0.0.1'
  port: 3307
  dbname: 'admin'
  username: 'xiaoyuan'
  password: 'Lbr1234%'

zap:
  level: 'debug'
  filename: './log/all.log'
  maxSize: 200
  maxAge: 7
  maxBackups: 10
  log-in-console: false

redis:
  db: 0
  addr: '127.0.0.1:6380'
  password: ''